{% set name = "pydaily" %}
{% set version = "0.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pydaily-{{ version }}.tar.gz
  sha256: 081bf3b4104d797c30620956e588717edbe42d9a077ababb4c393f5fa8dbb224

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy >=1.20.0
    - opencv >=4.4.0.40
    - scikit-image >=0.18.0
    - pandas >=1.2.0
    - deepdish >=0.3.6
    - setuptools

test:
  requires:
    - python {{ python_min }}
  imports:
    - pydaily
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/PingjunChen/pydaily
  summary: Daily python utility functions.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
